export interface Event {
  name: string
  edition?: string
  time: string
  location: string
  flag: string
  url: string
  continent: string
  month: string
  startDay: number
  endDay: number
  eventType: "conference" | "workshop" | "meetup" | "festival" | "online"
  description?: string
  speakers?: string[]
  venue?: string
}

export const eventsData: Event[] = [
  // January events
  {
    name: "Bounce",
    edition: "1st Edition",
    time: "All Day",
    location: "Dublin",
    flag: "🇮🇪",
    url: "https://www.bouncecreative.ie/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "January",
    startDay: 9,
    endDay: 10,
    eventType: "conference",
    description:
      "Bounce is Ireland's premier creative conference bringing together designers, artists, and innovators for two days of inspiration and networking.",
    speakers: ["Sarah O'Brien", "Mark Kelly", "Emma Walsh"],
    venue: "Convention Centre Dublin, Spencer Dock",
  },
  {
    name: "It's All Graphic #12",
    time: "8 to 11pm at Pakhuis de Zwijger",
    location: "Amsterdam",
    flag: "🇳🇱",
    url: "http://wimcrouwelinstituut.nl/nl/activities/news/it-s-all-graphic-12?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "January",
    startDay: 20,
    endDay: 20,
    eventType: "meetup",
    description:
      "A monthly meetup celebrating graphic design culture with talks, presentations, and networking in Amsterdam's creative hub.",
    venue: "Pakhuis de Zwijger, Piet Heinkade 179",
  },
  {
    name: "Snow Camp",
    time: "All Day",
    location: "Grenoble",
    flag: "🇫🇷",
    url: "https://snowcamp.io/en/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "January",
    startDay: 22,
    endDay: 24,
    eventType: "conference",
    description:
      "Snow Camp combines technology conferences with alpine skiing, offering a unique experience for developers and designers in the French Alps.",
    speakers: ["Jean-Pierre Martin", "Sophie Dubois"],
    venue: "World Trade Center Grenoble",
  },
  {
    name: "CTM Festival",
    time: "All Day",
    location: "Berlin",
    flag: "🇩🇪",
    url: "https://www.ctm-festival.de/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "January",
    startDay: 23,
    endDay: 31,
    eventType: "festival",
    description:
      "CTM Festival for Adventurous Music and Art explores the nexus of contemporary electronic and experimental music with visual art.",
    venue: "Various venues across Berlin",
  },
  {
    name: "PixelPerfect",
    edition: "1st Edition",
    time: "All Day",
    location: "London",
    flag: "🇬🇧",
    url: "https://pixelperfect.world/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "January",
    startDay: 24,
    endDay: 24,
    eventType: "conference",
    description:
      "PixelPerfect is a new conference dedicated to the craft of digital design, focusing on UI/UX excellence and design systems.",
    speakers: ["Dan Mall", "Jina Anne", "Brad Frost"],
    venue: "Barbican Centre, Silk Street",
  },
  {
    name: "Design Leadership Summit 2025",
    time: "All Day",
    location: "Toronto",
    flag: "🇨🇦",
    url: "https://designleadership.io/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "North America",
    month: "January",
    startDay: 29,
    endDay: 30,
    eventType: "conference",
    description:
      "The Design Leadership Summit brings together design leaders from around the world to discuss strategy, management, and the future of design.",
    speakers: ["Kim Goodwin", "Peter Merholz", "Kristin Skinner"],
    venue: "MaRS Discovery District",
  },
  {
    name: "DEMO Festival",
    time: "All Day",
    location: "Amsterdam",
    flag: "🇳🇱",
    url: "https://www.demofestival.com/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "January",
    startDay: 30,
    endDay: 30,
    eventType: "festival",
    description:
      "DEMO Festival celebrates motion design, animation, and visual effects with screenings, workshops, and industry talks.",
    venue: "Eye Filmmuseum, IJpromenade 1",
  },
  {
    name: "Design Leaders Conference",
    time: "All Day",
    location: "Dublin",
    flag: "🇮🇪",
    url: "https://www.designleadersconference.com/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "January",
    startDay: 30,
    endDay: 30,
    eventType: "conference",
    description:
      "A conference for design managers and executives to learn about building and scaling design teams effectively.",
    speakers: ["Colm Tuite", "Emmet Connolly"],
    venue: "The Mansion House, Dawson Street",
  },
  {
    name: "transmediale",
    time: "All Day",
    location: "Berlin",
    flag: "🇩🇪",
    url: "https://www.transmediale.de/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "January",
    startDay: 31,
    endDay: 31,
    eventType: "festival",
    description:
      "transmediale is a festival and year-round project exploring the cultural and political challenges of digital technologies.",
    venue: "Haus der Kulturen der Welt",
  },

  // February events
  {
    name: "CTM Festival",
    time: "All Day",
    location: "Berlin",
    flag: "🇩🇪",
    url: "https://www.ctm-festival.de/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "February",
    startDay: 1,
    endDay: 2,
    eventType: "festival",
    description:
      "CTM Festival for Adventurous Music and Art explores the nexus of contemporary electronic and experimental music with visual art.",
    venue: "Various venues across Berlin",
  },
  {
    name: "Blind Walls Film Fest",
    time: "All Day",
    location: "Breda",
    flag: "🇳🇱",
    url: "https://www.chasse.nl/nl/pQYLviG/blind-walls-film-fest-2025?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Europe",
    month: "February",
    startDay: 5,
    endDay: 9,
    eventType: "festival",
    description:
      "Blind Walls Film Fest showcases films about street art, murals, and urban creativity from around the world.",
    venue: "Chassé Theater, Claudius Prinsenlaan 8",
  },
  {
    name: "BITS",
    time: "All Day",
    location: "Bangkok",
    flag: "🇹🇭",
    url: "http://bitscon.asia/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Asia",
    month: "February",
    startDay: 13,
    endDay: 16,
    eventType: "conference",
    description:
      "BITS is Southeast Asia's leading design and technology conference, connecting creative professionals across the region.",
    speakers: ["Ling Chen", "Prasit Tangprasert", "Maya Wong"],
    venue: "Bangkok International Trade & Exhibition Centre",
  },
  {
    name: "Animatex",
    edition: "5th Edition",
    time: "All day",
    location: "Cairo",
    flag: "🇪🇬",
    url: "https://www.animatex.net/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Africa",
    month: "February",
    startDay: 20,
    endDay: 25,
    eventType: "festival",
    description:
      "Animatex is the Middle East and North Africa's premier animation festival, featuring screenings, workshops, and industry panels.",
    speakers: ["Ahmed Hassan", "Nour El-Din"],
    venue: "Cairo Opera House",
  },

  // March events
  {
    name: "Graphika Manilla",
    time: "All Day",
    location: "Manilla",
    flag: "🇵🇭",
    url: "https://graphikamanila.com/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Asia",
    month: "March",
    startDay: 1,
    endDay: 2,
    eventType: "conference",
    description:
      "Graphika Manila is the Philippines' largest design conference, inspiring creativity through world-class speakers and workshops.",
    speakers: ["Aaron Draplin", "Jessica Walsh", "Timothy Goodman"],
    venue: "Samsung Hall, SM Aura Premier",
  },
  {
    name: "DIBI Conference",
    time: "All Day",
    location: "Edinburgh",
    flag: "🇬🇧",
    url: "https://dibiconference.com/?ref=designeventsguide",
    continent: "Europe",
    month: "March",
    startDay: 5,
    endDay: 6,
    eventType: "conference",
    description:
      "DIBI (Design It, Build It) is a two-day conference featuring design and development tracks for digital professionals.",
    speakers: ["Ethan Marcotte", "Sarah Parmenter", "Val Head"],
    venue: "Dynamic Earth, Holyrood Road",
  },
  {
    name: "Paradiso",
    edition: "1st Edition",
    time: "All Day",
    location: "Mérida",
    flag: "🇲🇽",
    url: "https://paradisofest.com/?utm_source=designevents.guide&utm_medium=website&utm_campaign=guide",
    continent: "Latin America",
    month: "March",
    startDay: 12,
    endDay: 15,
    eventType: "festival",
    description:
      "Paradiso is a new creative festival in the heart of Mexico's Yucatan Peninsula, blending design, art, and cultural experiences.",
    speakers: ["Carlos Alonso", "Maria Rodriguez"],
    venue: "Gran Museo del Mundo Maya",
  },

  // September events
  {
    name: "Design Week Tokyo",
    edition: "3rd Edition",
    time: "All Day",
    location: "Tokyo",
    flag: "🇯🇵",
    url: "https://example.com",
    continent: "Asia",
    month: "September",
    startDay: 4,
    endDay: 7,
    eventType: "conference",
    description:
      "Design Week Tokyo showcases the best of Japanese and international design across multiple venues in the city.",
    speakers: ["Naoto Fukasawa", "Kenya Hara", "Tokujin Yoshioka"],
    venue: "Tokyo Midtown, Roppongi",
  },
  {
    name: "Creative Summit",
    time: "9am to 6pm",
    location: "Melbourne",
    flag: "🇦🇺",
    url: "https://example.com",
    continent: "Oceania",
    month: "September",
    startDay: 15,
    endDay: 17,
    eventType: "conference",
    description:
      "Creative Summit brings together Australia's most innovative designers and creative directors for three days of inspiration.",
    speakers: ["Vince Frost", "Gemma O'Brien"],
    venue: "Melbourne Convention and Exhibition Centre",
  },
  {
    name: "UX Fest Online",
    time: "All Day",
    location: "Online",
    flag: "📡",
    url: "https://example.com",
    continent: "Online",
    month: "September",
    startDay: 22,
    endDay: 24,
    eventType: "online",
    description:
      "UX Fest Online is a virtual conference bringing together UX professionals from around the world for workshops and talks.",
    speakers: ["Jared Spool", "Kim Goodwin", "Steve Krug"],
    venue: "Virtual Event",
  },
]
